#!/usr/bin/env zsh

export DISPLAY=:0
if command -v xhost >/dev/null 2>&1; then
    xhost +SI:localuser:$(whoami)
fi

$(which java) sshGui.java &

{ echo keydown leftmeta; echo keydown leftshift; echo key space;} | dotool

if (swaymsg -t get_tree | grep -q 'SSH Server Selection'); then
else 
    { echo keydown leftmeta; echo keydown leftshift; echo key space;} | dotool
fi
